name: Homebrew Release

on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula to release Homebrew'
        default: twilio
      version:
        description: 'Release version - Same as CLI version'
        required: true
      sha:
        description: 'SHA of tar file created by oclif'
      pre-release:
        description: 'If it is a prerelease send true as input'
        default: 'false'
        
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout to homebrew
       uses: actions/checkout@v2
     - name: Update Home Brew with latest sha and version
       run: |
         # Add condition if sha is not given do a release without updating anything
         echo "${{github.event.inputs.formula}}"
         echo "${{github.event.inputs.version}}"
         echo "${{github.event.inputs.sha}}"
         version_pattern="[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]*"
         formula_path="Formula/${{github.event.inputs.formula}}.rb"
         sed -i.bak "s/${{github.event.inputs.formula}}-v$version_pattern/${{github.event.inputs.formula}}-v${{github.event.inputs.version}}/g" $formula_path
         sed -i.bak 's/version .*/version ${{github.event.inputs.version}}/' $formula_path
         sed -i.bak 's/sha256 .*/sha256 ${{github.event.inputs.sha}}/' $formula_path
         git config --global user.email "lakshmiravali.rimmalapudi@gmail.com"
         git config --global user.name "lakshmiravali"
         branch=$(git branch --show-current)
         echo "Current branch: $branch"
         git add -A
         git commit -m "Release ${{github.event.inputs.version}}"
         git push origin $branch
  release:
    runs-on: ubuntu-latest
    needs: [update]
    steps:
     - name: Checkout to homebrew
       uses: actions/checkout@v2
     - run: git pull
     - name: Create a GitHub release
       uses: ncipollo/release-action@v1
       with:
        tag: ${{github.event.inputs.version}}
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: ${{github.event.inputs.pre-release}}
